"""empty message

Revision ID: d3a322e3b4df
Revises: 
Create Date: 2025-03-21 15:30:25.366917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3a322e3b4df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kselectionstatistic', schema=None) as batch_op:
        batch_op.alter_column('combined',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kselectionstatistic', schema=None) as batch_op:
        batch_op.alter_column('combined',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###